In [1]:
import numpy as np

In [6]:
# Creating a 1D array = Vector
a1d = np.array([1, 2, 3, 4, 5])



a1d

array([1, 2, 3, 4, 5])

In [18]:
a2d = np.array([[1, 2, 3], [4, 5, 6]])

In [19]:
a2d #2D array = Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [21]:
a3d #Matrix with (3rows x 3columns)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
a3d.shape

(2, 3, 3)

In [23]:
a2d.shape

(2, 3)