In [18]:
import numpy as np

In [19]:
# Creating a 1D array = Vector
a1d = np.array([1, 2, 3, 4, 5])

In [20]:
a1d

array([1, 2, 3, 4, 5])

In [21]:
a2d = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
a2d #2D array = Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a2d.ndim

2

In [27]:
a3d = np.array([[[1,2,3,3],[4,5,6,5]],[[1,2,3,5],[7,8,9,6]]])

In [25]:
a3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [28]:
a3d.dtype

dtype('int64')

In [32]:
a3d.size #it tells the number of entries in the matrix rows

16

In [33]:
a3d.ndim  #n dimension that we can as any dimension of matrix which is runing

3

In [34]:
type(a3d)

numpy.ndarray

In [35]:
import pandas as pd

In [36]:
df = pd.DataFrame(a2d)

In [37]:
df

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
#end of lecture 107