# we will learn /Creating numpy arrays \

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
test_array = np.array([1,2,3])

In [6]:
test_array

array([1, 2, 3])

In [7]:
#Zeros
#Ones
#randoms
ones = np.ones((2,3))

In [8]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
type(ones)

numpy.ndarray

In [10]:
zeros = np.zeros((2,3))

In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0,10,2)   #A range to understand if u gets confusd

In [13]:
range_array

array([0, 2, 4, 6, 8])

In [14]:
#np.random.randint(start, stop, size=(3,5))
#np.random.randint(0, 10, size=(3,5))
random_matrix = np.random.randint(0, 10, size=(3,5)) # Manual Range start stop 3row and 5 columns

In [15]:
random_matrix

array([[7, 8, 7, 3, 3],
       [8, 5, 2, 5, 5],
       [5, 9, 6, 8, 1]], dtype=int32)

In [16]:
random_matrix.size

15

In [19]:
random_matrix.shape

(3, 5)

In [20]:
random_matrix = np.random.rand(3,5)   #Auto range 0-1 

In [22]:
random_matrix

array([[0.88618894, 0.01761955, 0.59571096, 0.58604598, 0.32849351],
       [0.12976255, 0.55917385, 0.76025823, 0.55590697, 0.97962256],
       [0.59042987, 0.81896996, 0.8327926 , 0.71155973, 0.0436773 ]])

In [23]:
random_matrix.sum()

np.float64(8.396212565166309)

# end of lecture