In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
random_matrix = np.random.randint(0, 10, size=(3,5)) #Each run produces different numbers unless a random seed is set.

In [5]:
random_matrix #Each run produces different numbers unless a random seed is set.

array([[0, 8, 6, 3, 0],
       [9, 7, 7, 8, 3],
       [1, 1, 6, 6, 6]], dtype=int32)

In [6]:
random_matrix.size

15

In [7]:
random_matrix.shape

(3, 5)

In [8]:
random_matrix = np.random.rand(3,5)   #Auto range 0-1 

In [9]:
random_matrix

array([[0.16185768, 0.0827778 , 0.03788412, 0.49892311, 0.99562381],
       [0.59376222, 0.62801281, 0.66692924, 0.01227445, 0.06190353],
       [0.48301387, 0.71733853, 0.45581288, 0.00614917, 0.31174406]])

#  👍 — if you create a random array and want your teammate to see the same result, you need to set a seed before generating it. The seed ensures that the random number generator produces the same sequence every time, regardless of who runs the code or where it’s run.

# The seed() function in NumPy (and random number generation in general) is used to set the starting state of the random number generator. By fixing this starting point, you make the sequence of random numbers predictable and reproducible.

How it works
np.random.seed(42) initializes the random generator with the seed value 42.

Every time you run code after setting the same seed, you’ll get the same random numbers.

Different seeds (e.g., 1, 7, 123) produce different sequences, but each seed always produces its own consistent sequence.

In [10]:
#Seed
np.random.seed(seed=0)
random_matrix = np.random.rand(3,5)   #Auto range 0-1 

In [12]:
random_matrix

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])