# Accessing Elements

In [47]:
import pandas as pd

In [48]:
import numpy as np

In [49]:
a2d = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a2d[0]

array([1, 2, 3])

In [52]:
a3d = np.array([[[1,2,3,3],[4,5,6,5]],[[1,2,3,5],[7,8,9,6]]])

In [53]:
a3d

array([[[1, 2, 3, 3],
        [4, 5, 6, 5]],

       [[1, 2, 3, 5],
        [7, 8, 9, 6]]])

In [54]:
a3d[:3]

array([[[1, 2, 3, 3],
        [4, 5, 6, 5]],

       [[1, 2, 3, 5],
        [7, 8, 9, 6]]])

In [55]:
a3d[:2]

array([[[1, 2, 3, 3],
        [4, 5, 6, 5]],

       [[1, 2, 3, 5],
        [7, 8, 9, 6]]])

In [57]:
a3d[:2,:1,:2]
# English: a3d[:2, :1, :2] means: first 2 blocks, first row only, first 2 columns.
# Roman Urdu: a3d[:2, :1, :2] ka matlab hai: pehle 2 blocks, sirf pehli row, aur pehle 2 columns.
#This is a great moment to reinforce axis-based slicing in 3D arrays.

array([[[1, 2]],

       [[1, 2]]])

In [77]:
# arandom = np.random.randint(10,size=(3,2))
#arandom = np.random.randint(10,size=(3,4,5))
arandom = np.random.randint(10,size=(2,3,4,5))

In [76]:
arandom

array([[[[8, 3, 2, 1, 2],
         [1, 4, 0, 1, 2],
         [2, 4, 0, 6, 8],
         [3, 5, 6, 4, 2]],

        [[4, 9, 1, 6, 9],
         [6, 1, 6, 3, 1],
         [8, 2, 9, 9, 7],
         [4, 1, 1, 9, 4]],

        [[2, 1, 0, 3, 3],
         [9, 5, 7, 9, 8],
         [9, 3, 9, 0, 0],
         [9, 5, 2, 8, 9]]],


       [[[5, 2, 8, 1, 4],
         [7, 7, 3, 8, 3],
         [5, 2, 8, 5, 3],
         [7, 5, 8, 1, 8]],

        [[2, 0, 4, 6, 6],
         [2, 6, 1, 5, 7],
         [5, 5, 8, 4, 0],
         [1, 4, 8, 8, 4]],

        [[6, 5, 8, 6, 8],
         [4, 8, 2, 5, 4],
         [9, 7, 1, 1, 7],
         [7, 5, 6, 1, 9]]]], dtype=int32)

In [83]:
arandom[:1,:1,:1,:1]

array([[[[0]]]], dtype=int32)

# English: In 3D arrays, each block is a 2D matrix. In 4D arrays, each block is a 3D cube.
# Roman Urdu: 3D arrays mein har block ek 2D matrix hota hai. 4D arrays mein har block ek 3D cube hota hai.
# Rows aur columns block ke andar hote hain.
# English:
# Axis 0 → Block (a 3D cube)
# Axis 1 → Matrix inside the block
# Axis 2 → Row inside the matrix
# Axis 3 → Column inside the row

# Roman Urdu:
# Axis 0 → Block ya cube
# Axis 1 → Matrix block ke andar
# Axis 2 → Row matrix ke andar
# Axis 3 → Column row ke andar
