# 111.Array Manipulation

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
a1d = np.array([1, 2, 3])

In [11]:
a1d

array([1, 2, 3])

In [12]:
ones = np.ones((2,3))

In [13]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a1d+ones #broad castng

array([[2., 3., 4.],
       [2., 3., 4.]])

In [32]:
a2d = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a3d = np.array([[[1,2,3,3],[4,5,6,5]],[[1,2,3,5],[7,8,9,6]]])

In [20]:
a3d

array([[[1, 2, 3, 3],
        [4, 5, 6, 5]],

       [[1, 2, 3, 5],
        [7, 8, 9, 6]]])

# is a 2D NumPy array with two rows and three columns, containing floating-point numbers. Based on the surrounding page context — a Jupyter Notebook titled "111 Array Manipulation" — this array likely results from a slicing or broadcasting operation applied to a higher-dimensional array.

# 📊 Likely Meaning in Context
Given the notebook’s focus on array manipulation, this array could be:

A slice from a 3D or 4D array, extracting a 2D matrix.

A broadcasted result, where a smaller array was expanded to match the shape of another.

A transformation output, such as reshaping or stacking.

The repeated rows suggest either:

A slice like array[:, :3] from a larger array with identical rows.

A broadcasted row [2., 3., 4.] across two rows.
# 🧑‍🏫 Teaching Tip (English + Roman Urdu)
# English: This is a 2D array with 2 rows and 3 columns, possibly sliced or broadcasted from a larger array.
# Roman Urdu: Ye ek 2D array hai jisme 2 rows aur 3 columns hain, shayad kisi bade array se slice ya broadcast hua hai.


In [21]:
a1d-ones  #subraction

array([[0., 1., 2.],
       [0., 1., 2.]])

In [22]:
a1d*ones #multiplication

array([[1., 2., 3.],
       [1., 2., 3.]])

In [28]:
t = a3d[:2,:2,:3]

In [34]:
a2d*t

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 1,  4,  9],
        [28, 40, 54]]])

In [35]:
a1d/a2d

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [36]:
a1d//a2d

array([[1, 1, 1],
       [0, 0, 0]])

In [37]:
a1d**2

array([1, 4, 9])

In [38]:
np.square(a1d)

array([1, 4, 9])

In [39]:
a2d%2

array([[1, 0, 1],
       [0, 1, 0]])

In [ ]:
end of lecture 111 at 52:45sec