## 115. Dot Product

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.random.seed(seed=0)
matrix_1 = np.random.randint(10,size=(4,3))
matrix_2 = np.random.randint(10,size=(4,3))

In [4]:
matrix_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]], dtype=int32)

In [5]:
matrix_2

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]], dtype=int32)

## Element wise multiplication kia hoti hai

In [6]:
matrix_1*matrix_1

array([[25,  0,  9],
       [ 9, 49, 81],
       [ 9, 25,  4],
       [16, 49, 36]], dtype=int32)

In [7]:
matrix_1*matrix_2

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]], dtype=int32)

In [8]:
matrix_1.dot(matrix_2) #because we have take transpose to make balance in dimensions


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [12]:
matrix_1.dot(matrix_2.T) #just like we multiplied matrices in 9th and 11th class mathematics after taking transpose by swap=by changing rows of matrix into columns

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]], dtype=int32)

In [13]:
matrix_1.shape,matrix_2.T.shape

((4, 3), (3, 4))

# here is link for matrix multiplications ::http://matrixmultiplication.xyz/