# Rehsape and  Transpose 


In [1]:
import pandas as pd

In [2]:
import numpy as np

## Step 1: Original array
a2d = np.array([[1,2,3],[5,6,7]])

print(a2d.shape)   # (2, 3)


In [3]:
a2d = np.array([[1,2,3],[5,6,7]])

In [4]:
a2d

array([[1, 2, 3],
       [5, 6, 7]])

## 👉 A simple way to explain to students:
“.shape is like asking NumPy: how many rows and how many columns are in my table?”


In [5]:
a2d.shape

(2, 3)

# Step 2: Transpose (.T)
Transpose flips rows ↔ columns.
So your array becomes:

1	5
2	6
3	7

In [9]:
a2d.T.shape 
#Transposed array (a2d.T)
# Transpose means flip rows and columns.

(3, 2)

In [10]:
a2d.T 
#👉 Easy way to explain:
# Transpose is like rotating the table so that rows become columns and columns become rows.

array([[1, 5],
       [2, 6],
       [3, 7]])

# 1. What is reshape?
In NumPy, reshape changes the shape (rows × columns) of an array without changing the data.

Think of it like rearranging chairs in a classroom:

Same number of chairs (data).

Different arrangement (rows and columns).

In [11]:
#Rehsape
a2d.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[5],
        [6],
        [7]]])

In [12]:
a2d.reshape(2,3,1).shape

(2, 3, 1)