# 119.Sorting Arrays 33:25 min

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
np.random.seed(seed=0)
random_matrix = np.random.randint(10,size=(3,5))
random_matrix

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

# The function call np.sort(random_matrix) in NumPy sorts the elements of the array along a specified axis. By default:

### If random_matrix is a 1D array, it simply returns a sorted version of that array.

### If random_matrix is a 2D array (matrix), np.sort sorts each row independently, in ascending order, along the last axis (axis = -1).

### You can control the sorting axis using the axis parameter:

### np.sort(random_matrix, axis=0) → sorts each column.

### np.sort(random_matrix, axis=1) → sorts each row.

### If you want the entire matrix flattened and sorted as one long array, you can use:

### python
#### np.sort(random_matrix, axis=None)
### Example
### python
### import numpy as np

### random_matrix = np.random.randint(1, 10, (3, 3))
### print("Original Matrix:\n", random_matrix)

### print("\nRow-wise sort:\n", np.sort(random_matrix, axis=1))
### print("\nColumn-wise sort:\n", np.sort(random_matrix, axis=0))
### print("\nFlattened sort:\n", np.sort(random_matrix, axis=None))
### This will show you how the sorting behaves differently depending on the axis.

In [9]:
np.sort(random_matrix #yeh har row ko ascending order m tarteeb de ga HAHAHAHAH

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]], dtype=int32)

In [7]:
np.sort(random_matrix, axis=1) #yeh BHE har row ko ascending order m tarteeb de ga HAHAHAHAH axis=1 rows sorting ka bata h

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]], dtype=int32)

In [27]:
np.sort(random_matrix, axis=0) #yeh  har column ko ascending order m tarteeb de ga HAHAHAHAH axis=0 elements sorting ascending in columns sorting ka bata h

array([[5, 0, 3, 2, 1],
       [7, 3, 5, 3, 4],
       [9, 6, 8, 8, 7]], dtype=int32)

### Exactly 👍 — you’ve nailed the distinction:

np.argsort(random_matrix, axis=0) → gives the indices that would sort each column.
It doesn’t change the matrix itself, but tells you the order of rows for ascending values in each column.

np.sort(random_matrix, axis=1) → directly gives the sorted elements row by row.
Each row is rearranged into ascending order.

Quick Demo
python
import numpy as np

random_matrix = np.array([[7, 2, 9],
                          [1, 8, 3],
                          [5, 4, 7]])

print("Original Matrix:\n", random_matrix)

## Indices for column-wise sort
col_indices = np.argsort(random_matrix, axis=0)
print("\nIndices for column-wise sort:\n", col_indices)

## Row-wise sorted elements
row_sorted = np.sort(random_matrix, axis=1)
print("\nRow-wise sorted matrix:\n", row_sorted)
Output (example run)
Code
Original Matrix:
 [[7 2 9]
  [1 8 3]
  [5 4 7]]

Indices for column-wise sort:
 [[1 0 1]
  [2 2 2]
  [0 1 0]]

Row-wise sorted matrix:
 [[2 7 9]
  [1 3 8]
  [4 5 7]]
So:

## argsort → gives you the map of positions (indices).

## sort → gives you the actual sorted values.

### Mental model (super important)

## sort → “Just give me sorted values, I don’t care how.”

## argsort → “Tell me the ranking/order so I can reuse it elsewhere.”

## That’s why argsort is huge in:

### ML feature ranking

### Top-k problems

### Sorting one array based on another

### Pandas / NumPy alignment logic

In [28]:
random_matrix

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

In [29]:
np.argsort(random_matrix, axis=0)  #argsort index dega#np.sort(random_matrix, axis=0) this gives the index of elemnts in column wise

array([[0, 0, 0, 1, 2],
       [2, 1, 1, 0, 1],
       [1, 2, 2, 2, 0]])

In [3]:
# Explanation
# np.argmin(random_matrix, axis=0) → looks down each column and returns the row index of the smallest element in that column.

# For your matrix:

# Code
# Column 0 → [5, 9, 7] → min = 5 → index 0
# Column 1 → [0, 3, 6] → min = 0 → index 0
# Column 2 → [3, 5, 8] → min = 3 → index 0
# Column 3 → [3, 2, 8] → min = 2 → index 1
# # Column 4 → [7, 4, 1] → min = 1 → index 2
# So the result is:

# Code
# [0 0 0 1 2]
# # Key Difference
# np.argmin(..., axis=0) → gives indices of minimum values column-wise.

# np.sort(..., axis=1) → gives the actual sorted values row-wise.

# 👉 In short: argmin/argsort = positions, sort = values.

In [30]:
np.argmin(random_matrix, axis=0)

array([0, 0, 0, 1, 2])

In [31]:
random_matrix

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

In [4]:
#Looking at each column:

# Column 0 → [5, 9, 7] → max = 9 → index 1

# Column 1 → [0, 3, 6] → max = 6 → index 2

# Column 2 → [3, 5, 8] → max = 8 → index 2

# Column 3 → [3, 2, 8] → max = 8 → index 2

# Column 4 → [7, 4, 1] → max = 7 → index 0

# So the result is:
# [1 2 2 2 0]

####### Key idea

# np.argmin(..., axis=0) → indices of minimum values column-wise.

# np.argmax(..., axis=0) → indices of maximum values column-wise.

# np.sort(..., axis=1) → actual sorted values row-wise.

In [24]:
np.argmax(random_matrix, axis=0)

array([1, 2, 2, 2, 0])

# axis = 0   represents column
## and
# axis = 1  represents rows