In [1]:
sk_learn_steps =[
    "1: Getting the Data Ready"
    "2: Choosing Machine Learning Model"
    "3: Fit Model"
    "4: Evaluate Model"
    "5: Improve Model"
    "6: Saving the Model"
    "7: Summary"
]

# 1 : Getting the Data Ready¶
### 1.1 Split data into features and label,
 ### (independent vs dependent variable),X,y
### 1.2 Filling missing values
### 1.3 Converting data Types

In [2]:
#standard Imports jo har haal m hum ny import krn he hoty h
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline



# 149 Step 1 Getting Data Ready Part 1¶
#### now
### 1.2 Converting data types

In [3]:
phone_data = pd.read_csv("../section 18 Scikit-Learn Part 02/phone_data_larg.csv")
phone_data

Make Colour  Memory(kb)  Sim Cards    Price
0        Nokia  White      150043          4  $400.00
1      Samsung    Red       87899          4  $500.00
2        Nokia   Blue       32549          3  $700.00
3       Iphone  Black       11179          5  $220.00
4    Motorolla  White      213095          4  $350.00
..         ...    ...         ...        ...      ...
995      Nokia  Green       99213          4  $450.00
996    Samsung   Blue       45698          4  $750.00
997    Samsung   Blue       54738          4  $700.00
998      Nokia  White       60000          4  $625.00
999  Motorolla  White       31600          4  $970.00

[1000 rows x 5 columns]

In [4]:
phone_data.dtypes

Make            str
Colour          str
Memory(kb)    int64
Sim Cards     int64
Price           str
dtype: object

In [5]:
phone_data['Price'] = phone_data['Price'].str[:-2]
phone_data['Price']

0      $400.
1      $500.
2      $700.
3      $220.
4      $350.
       ...  
995    $450.
996    $750.
997    $700.
998    $625.
999    $970.
Name: Price, Length: 1000, dtype: str

In [6]:
#regex= True is added it is in newer versions of pandas in in older 
phone_data['Price'] = phone_data['Price'].str.replace(r"[\$,\. ]", "", regex=True)  # remove $, commas, dots, spaces.astype(int)
phone_data['Price']

0      400
1      500
2      700
3      220
4      350
      ... 
995    450
996    750
997    700
998    625
999    970
Name: Price, Length: 1000, dtype: str

In [7]:
phone_data

Make Colour  Memory(kb)  Sim Cards Price
0        Nokia  White      150043          4   400
1      Samsung    Red       87899          4   500
2        Nokia   Blue       32549          3   700
3       Iphone  Black       11179          5   220
4    Motorolla  White      213095          4   350
..         ...    ...         ...        ...   ...
995      Nokia  Green       99213          4   450
996    Samsung   Blue       45698          4   750
997    Samsung   Blue       54738          4   700
998      Nokia  White       60000          4   625
999  Motorolla  White       31600          4   970

[1000 rows x 5 columns]

In [8]:

from sklearn.model_selection import train_test_split

In [9]:
X = phone_data.drop('Price', axis=1)
y = phone_data['Price']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X,y
    

(          Make Colour  Memory(kb)  Sim Cards
 0        Nokia  White      150043          4
 1      Samsung    Red       87899          4
 2        Nokia   Blue       32549          3
 3       Iphone  Black       11179          5
 4    Motorolla  White      213095          4
 ..         ...    ...         ...        ...
 995      Nokia  Green       99213          4
 996    Samsung   Blue       45698          4
 997    Samsung   Blue       54738          4
 998      Nokia  White       60000          4
 999  Motorolla  White       31600          4
 
 [1000 rows x 4 columns],
 0      400
 1      500
 2      700
 3      220
 4      350
       ... 
 995    450
 996    750
 997    700
 998    625
 999    970
 Name: Price, Length: 1000, dtype: str)

In [10]:
#Build Ml Model
from sklearn.ensemble import RandomForestRegressor


phone_model = RandomForestRegressor()
phone_model.fit(X_train, y_train)
phone_model.score(X_test,y_test) 
#this cell will raise an error to overcome  below cell



ValueError: could not convert string to float: 'Samsung'

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 
#The ColumnTransformer encodes categorical features into numeric arrays.

features_cat = ["Make","Colour","Sim Cards"]
hottie = OneHotEncoder()

transformer = ColumnTransformer([("Onehottie",hottie,features_cat)],remainder = "passthrough")#remainder="passthrough" keeps your numeric columns untouched.
transformed_X = transformer.fit_transform(X)
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  150043.0
1    0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   87899.0
2    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   32549.0
3    1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   11179.0
4    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  213095.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0   99213.0
996  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   45698.0
997  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   54738.0
998  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   60000.0
999  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   31600.0

[1000 rows x 13 columns]

# That notebook section you’re looking at, 
# 151 Getting Data Anatomy of Conversion,
its just explainantion...... of conversion string o numeric

# 152 ..Getting Data::: Second  Method of Conversion

In [ ]:
 # 2nd method for conversion
transformed_new = pd.get_dummies(phone_data[["Make","Colour","Sim Cards"]])
transformed_new.astype(float)

Sim Cards  Make_Iphone  Make_Motorolla  Make_Nokia  Make_Samsung  \
0          4.0          0.0             0.0         1.0           0.0   
1          4.0          0.0             0.0         0.0           1.0   
2          3.0          0.0             0.0         1.0           0.0   
3          5.0          1.0             0.0         0.0           0.0   
4          4.0          0.0             1.0         0.0           0.0   
..         ...          ...             ...         ...           ...   
995        4.0          0.0             0.0         1.0           0.0   
996        4.0          0.0             0.0         0.0           1.0   
997        4.0          0.0             0.0         0.0           1.0   
998        4.0          0.0             0.0         1.0           0.0   
999        4.0          0.0             1.0         0.0           0.0   

     Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0             0.0          0.0           0.0         0.0           1.0  
1             0.0          0.0           0.0         1.0           0.0  
2             0.0          1.0           0.0         0.0           0.0  
3             1.0          0.0           0.0         0.0           0.0  
4             0.0          0.0           0.0         0.0           1.0  
..            ...          ...           ...         ...           ...  
995           0.0          0.0           1.0         0.0           0.0  
996           0.0          1.0           0.0         0.0           0.0  
997           0.0          1.0           0.0         0.0           0.0  
998           0.0          0.0           0.0         0.0           1.0  
999           0.0          0.0           0.0         0.0           1.0  

[1000 rows x 10 columns]

In [ ]:
# # # Lets refit the model
# X_train,X_test,y_train,y_test =train_test_split(transformed_X,y,test_size=2.0)
# phone_model.fit(X_train,y_train); old but error

#Equivalent ways to split 80/20 #working
# X_train, X_test, y_train, y_test = train_test_split(
#     transformed_X, y, test_size=0.2, random_state=42
#)

#Or using train_size 20/80 rule # working
X_train, X_test, y_train, y_test = train_test_split(
    transformed_X, y, train_size=0.8, random_state=42
)
phone_model.fit(X_train,y_train)

RandomForestRegressor()

In [ ]:
# 1. Clean the Price column (Remove $, commas, and the extra dot)
# We use .str.replace with a regular expression
phone_data["Price"] = phone_data["Price"].str.replace(r'[\$,]', '', regex=True).astype(float)

# 2. Re-assign 'y' now that it is a numeric float
y = phone_data["Price"]

# 3. Now run your split and fit
X_train, X_test, y_train, y_test = train_test_split(
    transformed_X, y, train_size=0.8, random_state=42
)

phone_model.fit(X_train, y_train)
print("Model fitted successfully!")

Model fitted successfully!


In [ ]:
phone_model.score(X_test,y_test)

1.0

# 153.Getting Data ,Missing Values

In [ ]:
phone_missing_values = pd.read_csv('../section 18 Scikit-Learn Part 02/phone_data_missing_values.csv')

In [ ]:
phone_missing_values

Make Colour  Memory(kb)  Sim Cards    Price
0       Nokia  White    150043.0        4.0  $400.00
1     Samsung    Red     87899.0        4.0  $500.00
2         zte    NaN         NaN        NaN      NaN
3       Nokia   Blue     32549.0        3.0  $700.00
4      Iphone  Black     11179.0        5.0  $220.00
5   Motorolla  White    213095.0        4.0  $350.00
6      Iphone    NaN         NaN        NaN      NaN
7       Nokia  Green     99213.0        4.0  $450.00
8     Samsung   Blue     45698.0        4.0  $750.00
9     Samsung   Blue     54738.0        4.0  $700.00
10      Nokia  White     60000.0        4.0  $625.00
11  Motorolla  White     31600.0        4.0  $970.00
12    Samsung    NaN         NaN        NaN      NaN

In [ ]:
phone_missing_values.isna().sum()


Make          0
Colour        3
Memory(kb)    3
Sim Cards     3
Price         3
dtype: int64

In [ ]:
# # Fill NaN in Make column
########################################################################
# 1st #Avoid this method
# phone_missing_values["Make"].fillna("missing", inplace=True)

# # Fill NaN in Colour column
# phone_missing_values["Colour"].fillna("missing", inplace=True)

# # Fill NaN in Memory (kb) column with mean
# phone_missing_values["Memory(kb)"].fillna(
#     phone_missing_values["Memory(kb)"].mean(), inplace=True)
# #so we have to skip such type of errors
#######################################################################
# 2nd way
#Safe Fixes
#corrected by copilot#Fill NaN in Make column
phone_missing_values["Make"] = phone_missing_values["Make"].fillna("missing")
phone_missing_values["Colour"] = phone_missing_values["Colour"].fillna("missing")
phone_missing_values["Memory(kb)"] = phone_missing_values["Memory(kb)"].fillna(
    phone_missing_values["Memory(kb)"].mean()
)
# Verify the result 
print(phone_missing_values.isnull().sum())
print(phone_missing_values.head())

# 3rd way  # this good way to show fine table
#################################### Fill multiple columns at once###
# ### More easy ###
# phone_missing_values.fillna({
#     "Make": "missing",
#     "Colour": "missing",
#     "Memory(kb)": phone_missing_values["Memory(kb)"].mean()
# }, inplace=True)


Make          0
Colour        0
Memory(kb)    0
Sim Cards     3
Price         3
dtype: int64
      Make   Colour  Memory(kb)  Sim Cards    Price
0    Nokia    White    150043.0        4.0  $400.00
1  Samsung      Red     87899.0        4.0  $500.00
2      zte  missing     78601.4        NaN      NaN
3    Nokia     Blue     32549.0        3.0  $700.00
4   Iphone    Black     11179.0        5.0  $220.00


In [ ]:
# it is not a good idea k ap jis m changes kr ry ho usy predict kro so,
phone_missing_values.dropna(inplace=True)

In [ ]:
phone_missing_values.isna().sum()

Make          0
Colour        0
Memory(kb)    0
Sim Cards     0
Price         0
dtype: int64

# 154 Getting Data Missing Values method 2
### Method 2 : Fill Nan values using sklearn

In [ ]:
phone_data_missing = pd.read_csv('../section 18 Scikit-Learn Part 02/phone_data_missing_values.csv')
phone_data_missing 

Make Colour  Memory(kb)  Sim Cards    Price
0       Nokia  White    150043.0        4.0  $400.00
1     Samsung    Red     87899.0        4.0  $500.00
2         zte    NaN         NaN        NaN      NaN
3       Nokia   Blue     32549.0        3.0  $700.00
4      Iphone  Black     11179.0        5.0  $220.00
5   Motorolla  White    213095.0        4.0  $350.00
6      Iphone    NaN         NaN        NaN      NaN
7       Nokia  Green     99213.0        4.0  $450.00
8     Samsung   Blue     45698.0        4.0  $750.00
9     Samsung   Blue     54738.0        4.0  $700.00
10      Nokia  White     60000.0        4.0  $625.00
11  Motorolla  White     31600.0        4.0  $970.00
12    Samsung    NaN         NaN        NaN      NaN

In [ ]:
phone_data_missing.isna().sum()

Make          0
Colour        3
Memory(kb)    3
Sim Cards     3
Price         3
dtype: int64

In [ ]:
phone_data_missing.dropna(subset=["Price"], inplace=True)
phone_data_missing.isna().sum()

Make          0
Colour        0
Memory(kb)    0
Sim Cards     0
Price         0
dtype: int64

In [ ]:
# Split X and y 
X = phone_data_missing.drop('Price',axis=1)
y = phone_data_missing['Price']

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
import pandas as pd

# Column groups
cat_cols = ['Make', 'Colour']
num_cols = ['Sim Cards','Memory(kb)']

# Imputers
cat_imputer = SimpleImputer(strategy='constant', fill_value='missing')
num_imputer = SimpleImputer(strategy='mean')

# ColumnTransformer
imputer = ColumnTransformer(
    transformers=[
        ('cat', cat_imputer, cat_cols),
        ('num', num_imputer, num_cols)
    ]
)

# Apply imputation
phone_data_filled_X = imputer.fit_transform(X)

# Convert back to DataFrame
phone_data_filled_X = pd.DataFrame(
  phone_data_filled_X,
    columns=cat_cols + num_cols
)

phone_data_filled_X


Make Colour Sim Cards Memory(kb)
0      Nokia  White       4.0   150043.0
1    Samsung    Red       4.0    87899.0
2      Nokia   Blue       3.0    32549.0
3     Iphone  Black       5.0    11179.0
4  Motorolla  White       4.0   213095.0
5      Nokia  Green       4.0    99213.0
6    Samsung   Blue       4.0    45698.0
7    Samsung   Blue       4.0    54738.0
8      Nokia  White       4.0    60000.0
9  Motorolla  White       4.0    31600.0

In [ ]:
X.dtypes

Make              str
Colour            str
Memory(kb)    float64
Sim Cards     float64
dtype: object

In [ ]:
phone_data_filled_X.isna().sum()


Make          0
Colour        0
Sim Cards     0
Memory(kb)    0
dtype: int64

# 155. Choosing Macgine Learning Model

# https://scikit-learn.org/stable/machine_learning_map.html

# 156.Using map to choose model
# Picking up Model for Regression
# Importing data,Boston Housing

In [ ]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
X, y = housing.data, housing.target


In [ ]:
df_california = pd.DataFrame(housing.data, columns=housing.feature_names) 
df_california["target"] = housing.target 
df_california.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [ ]:
len(df_california)

20640

#
# Lets try Ridge regression model

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Reproducibility
np.random.seed(1)

# Load California housing dataset
housing = fetch_california_housing()

# Build DataFrame
df_california = pd.DataFrame(housing.data, columns=housing.feature_names)
df_california["target"] = housing.target

# Split into train and test
X = df_california.drop("target", axis=1)
y = df_california["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Ridge regression
reg_model = Ridge()
reg_model.fit(X_train, y_train)

# Model score
print(reg_model.score(X_test, y_test))


0.5965957761160752


# Let's Try RandomForestRegressor

In [ ]:
# to get better result or accuracy
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
import pandas as pd
import numpy as np

# Reproducibility
np.random.seed(1)

# Load dataset
housing = fetch_california_housing()
df_california = pd.DataFrame(housing.data, columns=housing.feature_names)
df_california["target"] = housing.target

# Split data
X = df_california.drop("target", axis=1)
y = df_california["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Random Forest
rf_model = RandomForestRegressor(n_estimators=200, random_state=1)
rf_model.fit(X_train, y_train)
print("RandomForestRegressor Accuracy:", rf_model.score(X_test, y_test))

# # Gradient Boosting
# gb_model = GradientBoostingRegressor(n_estimators=200, random_state=1)
# gb_model.fit(X_train, y_train)
# print("Gradient Boosting R^2:", gb_model.score(X_test, y_test))


RandomForestRegressor Accuracy: 0.80807564907151


# 158. Choosing Estimators for Classification Problem

In [ ]:
heart_disease = pd.read_csv('../section 18 Scikit-Learn Part 02/heart_disease_300.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   67    1   2       122   139    1        1      168      0      2.2      1   
1   57    0   0       154   232    1        2      108      0      4.1      1   
2   43    0   3       107   259    0        0       84      0      4.9      1   
3   71    1   2       185   166    1        2      188      1      5.7      2   
4   36    0   0       138   120    1        1       98      1      1.5      2   

   ca  thal  target  
0   1     0       0  
1   2     0       0  
2   3     1       1  
3   3     0       1  
4   0     1       0

In [ ]:
len(heart_disease)

303

# https://scikit-learn.org/stable/machine_learning_map.html

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.ensemble import GradientBoostingClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# 1. Reproducibility
np.random.seed(1)

# 2. Split data (Assuming heart_disease is already defined)
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 3. LinearSVC (Removed n_estimators, increased max_iter for convergence)
SVC_model = LinearSVC(max_iter=10000, random_state=1)
SVC_model.fit(X_train, y_train)
print(f"LinearSVC Accuracy: {SVC_model.score(X_test, y_test):.2%}")

# 4. Gradient Boosting (Switched to Classifier)
# gb_model = GradientBoostingClassifier(n_estimators=200, random_state=1)
# gb_model.fit(X_train, y_train)
# print(f"Gradient Boosting Accuracy: {gb_model.score(X_test, y_test):.2%}")

LinearSVC Accuracy: 40.98%


In [ ]:
 #we imported  RandomForestClassifier Model 
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
# To reproduce same result for fello ML Scientist
np.random.seed(1)
# Created Data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]
# Split into test and Train
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
#Instatiate Model
RFC_model = RandomForestClassifier()
RFC_model.fit(X_train,y_train)
#Check the score of the model
RFC_model.score(X_test,y_test)

0.45901639344262296

# 159. (3).Fit the Model

# stage 1 = Training 

# stage 2 = Testing

###  when you dont know what you are trying to solve then the worse thing you learn is hard work and hard work is not always good.

# 03 Make Prediction



In [ ]:
# 2: ways we can run the prediction
# prediction()
# predict_proba()
heart_disease = pd.read_csv("../section 18 Scikit-Learn Part 02/heart_disease_300.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   67    1   2       122   139    1        1      168      0      2.2      1   
1   57    0   0       154   232    1        2      108      0      4.1      1   
2   43    0   3       107   259    0        0       84      0      4.9      1   
3   71    1   2       185   166    1        2      188      1      5.7      2   
4   36    0   0       138   120    1        1       98      1      1.5      2   

   ca  thal  target  
0   1     0       0  
1   2     0       0  
2   3     1       1  
3   3     0       1  
4   0     1       0

In [ ]:
# ab hum data ko X aur y m change kry gy
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

In [ ]:
# Choosing Machine Learning Model
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()


In [ ]:
#Split data into test and Train
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
# 2. FIT the model (The missing step!)
# This is where the model learns the patterns in your data
clf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
# Evaluating Model
y_predicted = clf.predict(X_test)
y_predicted

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0])

In [ ]:
np.array(y_test) #Ground Reality Karwa Sach

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0])

In [ ]:
np.mean(y_predicted == y_test) #Method 1

np.float64(0.5245901639344263)

In [ ]:
clf.score(X_test,y_test) #Method 2

0.5245901639344263

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predicted) #Method 3

0.5245901639344263

# 161 . Step 3 predict proba method

In [ ]:
#predict_proba()

clf.predict(X_test)[:5]

array([1, 0, 1, 0, 0])

# 💡 Why this matters for Learning

If your model predicts a 1 with 51% confidence, it is technically "correct," but professionally "unreliable." If it predicts 1 with 99% confidence, you have a high-precision model. Learning to look at the probability teaches you how to tune your model's sensitivity.

In [ ]:
clf.predict_proba(X_test)[:5]

array([[0.48, 0.52],
       [0.7 , 0.3 ],
       [0.48, 0.52],
       [0.56, 0.44],
       [0.51, 0.49]])

In [ ]:
# Making Prediction on regression problem
df_california

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [ ]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(1)
#Create Data
X = df_california.drop('target',axis=1)
y =df_california["target"]
#Split into test and train
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
#instatiate Model
Regression_model = RandomForestRegressor().fit(X_train,y_train)
#Make prediction
predicted_y = Regression_model.predict(X_test)


In [ ]:
predicted_y[:5]

array([3.5471109, 0.63191  , 2.35045  , 1.2874   , 2.8893303])

In [ ]:
np.array(y_test[:5]) #Ground reality, krwa sach


array([3.55 , 0.707, 2.294, 1.125, 2.254])

In [ ]:
#Compare the prediction with ground reality
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,predicted_y)

0.32635206574612424

In [ ]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(1)

#Splitting Data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
clf = RandomForestClassifier().fit(X_train,y_train)
clf

RandomForestClassifier()

In [ ]:
### Pro Tip: Extracting the "Success" Probability
# When using `predict_proba()`, Scikit-Learn returns a column for every class. 
# In binary classification (0 or 1), you usually only care about the probability of **1**.
# Get probabilities for all classes
all_probs = clf.predict_proba(X_test)
#  Professional shortcut: Extract ONLY the probability of being '1'
# [:, 1] means "all rows, second column"
positive_confidence = all_probs[:, 1]
positive_confidence

array([0.5 , 0.52, 0.58, 0.61, 0.65, 0.46, 0.37, 0.34, 0.42, 0.6 , 0.35,
       0.47, 0.49, 0.45, 0.57, 0.35, 0.54, 0.59, 0.27, 0.6 , 0.54, 0.64,
       0.41, 0.59, 0.64, 0.36, 0.49, 0.31, 0.56, 0.55, 0.37, 0.34, 0.57,
       0.44, 0.53, 0.44, 0.67, 0.53, 0.53, 0.49, 0.42, 0.47, 0.4 , 0.52,
       0.49, 0.36, 0.5 , 0.5 , 0.44, 0.26, 0.34, 0.61, 0.38, 0.52, 0.51,
       0.17, 0.44, 0.38, 0.34, 0.46, 0.55])

In [ ]:
clf.score(X_train,y_train) #Can only run after fitting the model

1.0

In [ ]:
clf.score(X_test,y_test) #Can only run this after fitting the model

0.45901639344262296

In [ ]:
from sklearn.ensemble import  RandomForestRegressor
np.random.seed(4)
#create data 

X = df_california.drop("target",axis=1)
y = df_california["target"]

#split into test and train

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
#instiate model and fit
rf_model = RandomForestRegressor().fit(X_train,y_train)

In [ ]:
rf_model.score(X_test,y_test)

0.8030901336592146

In [ ]:
from sklearn.ensemble import  RandomForestClassifier
np.random.seed(4)
#create data 

X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

#split into test and train

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
#instiate model and fit
heart_model = RandomForestClassifier().fit(X_train,y_train)

In [ ]:
heart_model.score(X_test,y_test) #normal Score Method

0.639344262295082

# learn about cv

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(heart_model,X,y,cv=5, scoring=None)

array([0.50819672, 0.54098361, 0.49180328, 0.53333333, 0.55      ])

In [ ]:
heart_model.score(X_test,y_test),np.mean(cross_val_score(heart_model,X,y,cv=5))

(0.639344262295082, np.float64(0.49852459016393447))

# 165 Step 4 Accuracy(Classification Model)

# Classification model evaluation

In [ ]:
# 1 Accuracy
# 2 Area Under the Curve ROC
# 3 Confusion Matrix
# 4 Classification report


In [ ]:


#split into test and train

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
#instiate model and fit
heart_model = RandomForestClassifier().fit(X_train,y_train)
rom sklearn.model_selection import cross_val_score
from sklearn.ensemble import  RandomForestClassifier
np.random.seed(4)
#create data 

X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

In [ ]:
# 1 Accuracy

cross_val_score(heart_model,X,y,cv=5, scoring=None)

array([0.50819672, 0.54098361, 0.49180328, 0.53333333, 0.55      ])

In [ ]:
np.mean(cross_val_score(heart_model,X,y,cv=5, scoring=None))

np.float64(0.49852459016393447)

In [ ]:
print(f'Heart Disease Cross validation Accuracy: {np.mean(cross_val_score(heart_model,X,y,cv=5, scoring=None))*100:.2f}%')

Heart Disease Cross validation Accuracy: 52.16%


# 166. Step 4 Area Under the Curve Part 1
# # 2 Receiver Operating Characteristic Curve (ROC)

In [ ]:
# 2 Area Under the Curve(AUC) FROM CODE 83
# 2 Receiver Operating Characteristic Curve (ROC)


In [ ]:
#create test train data
from sklearn.metrics import roc_curve
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
# Fit the Model
clf.fit(X_train,y_train)
#Make prediction using predict_proba()
y_proba = clf.predict_proba(X_test)
y_proba[:5],y_test[:5]

(array([[0.66, 0.34],
        [0.35, 0.65],
        [0.57, 0.43],
        [0.54, 0.46],
        [0.47, 0.53]]),
 115    1
 278    1
 242    1
 4      0
 221    0
 Name: target, dtype: int64)

## in above output there are two columns of target prediction on right it has 1(means yes) predeiction and on left it is giving the 0(means No ) prediction
0.56

0.56

0.67

0.54

0.45

------
1 prediction means yes (right side column)

------


and simlarly you can understand for left 
column...



In [ ]:
len(y_proba)

61

In [ ]:
y_prob_positive = y_proba[:,1]

In [ ]:
# calculate fpr,tpr, threshold
fpr,tpr,threshold = roc_curve(y_test,y_prob_positive)

In [ ]:
fpr

array([0.        , 0.        , 0.03225806, 0.03225806, 0.06451613,
       0.06451613, 0.09677419, 0.09677419, 0.16129032, 0.19354839,
       0.22580645, 0.22580645, 0.25806452, 0.29032258, 0.35483871,
       0.38709677, 0.4516129 , 0.5483871 , 0.64516129, 0.74193548,
       0.74193548, 0.77419355, 0.87096774, 0.90322581, 0.96774194,
       0.96774194, 1.        ])